apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: odoo-web-svc
    env: prod
  name: odoo-web-svc
  namespace: ic-group
spec:
  ports:
  - name: 8069-8069
    port: 8069
    protocol: TCP
    targetPort: 8069
  selector:
    app: odoo-web
  type: LoadBalancer
status:
  loadBalancer: {}
